---
title: "ISD methods"
output: html_notebook
---
## setup

```{r setup, echo = F}
library(dplyr)
R.utils::sourceDirectory(path = here::here("lumpy-gappy", "R"))
```

## get data

```{r get data}

dat <- get_toy_portal_data()
dat_e <- add_energy_sizeclass(dat)
isd <- make_isd(dat_e)

```

## draw a sim

```{r draw sim}
set.seed(352)
communitypars <- get_community_pars(isd)

sim <- draw_sim(community_pars = communitypars)

sim_e <- add_energy_sizeclass(sim)

sim_isd <- make_isd(sim_e)

```
## plot ISDs

```{r plot ISDs}
isd_plot <- plot_isd(isd, "Empirical")
sim_isd_plot <- plot_isd(sim_isd, "Simulated") 

gridExtra::grid.arrange(isd_plot, sim_isd_plot, nrow = 1)

```

## fit GMMs

```{r fit gmms}

isds_to_analyze <- list(emp = isd,
                        sim = sim_isd)

gmms <- lapply(isds_to_analyze, fit_gmm)
```

## integrate density

```{r integrate density}

ids <- lapply(gmms, get_integrated_density)

id_plots <- lapply(ids, plot_integrated_density, threshold_lines = 0.05, pit_boundaries = F)

gridExtra::grid.arrange(grobs = id_plots, nrow = 1)
```


## find modes, pits, and troughs

```{r trough boundaries}

ids <- lapply(ids, add_all_pit_boundaries, threshold = 0.05)

id_plots <- lapply(ids, plot_integrated_density, pit_boundaries = T)

gridExtra::grid.arrange(grobs = id_plots, nrow = 1)
```

## summarize isd method results

```{r summarize isd methods}

isd_method_summaries <- lapply(ids, isd_methods_summary, threshold = 0.05) %>%
  dplyr::bind_rows(.id = "community")

```

## Sims at scale

```{r sims at scale, fig.width=18, fig.height=6}
communitypars <- get_community_pars(isd)

sims <- replicate(draw_sim(community_pars = communitypars), n = 10, simplify = F)

sims_e <- lapply(sims, add_energy_sizeclass)

sims_isd <- lapply(sims_e, make_isd)

sims_gmms <- lapply(sims_isd, fit_gmm)

sims_ids <- lapply(sims_gmms, get_integrated_density)

sims_ids_05 <- lapply(sims_ids, add_all_pit_boundaries, threshold = 0.05)
sims_ids_025 <- lapply(sims_ids, add_all_pit_boundaries, threshold = 0.025)
sims_ids_1 <- lapply(sims_ids, add_all_pit_boundaries, threshold = 0.1)



sims_isd_method_summaries_05 <- lapply(sims_ids_05, isd_methods_summary, threshold = 0.05)
sims_isd_method_summaries_025 <- lapply(sims_ids_025, isd_methods_summary, threshold = 0.025)
sims_isd_method_summaries_1 <- lapply(sims_ids_1, isd_methods_summary, threshold = 0.1)


sims_summary <-  dplyr::bind_rows(sims_isd_method_summaries_05, 
                                  sims_isd_method_summaries_025,
                                  sims_isd_method_summaries_1,
                                  .id = "sim")

sims_plots <- lapply(sims_ids[1:10], plot_integrated_density, threshold_lines = c(0.025, 0.05, 0.1))

sims_plots

sims_summary_plots <- plot_isd_methods_summary(sims_summary)

gridExtra::grid.arrange(grobs = sims_summary_plots, nrow = 1)

```

